### ISSUE TITLE
[Bug]: Install error on upgrade.sh

### ISSUE THREAD

**Issue by balpoint** [netbox-community/netbox-acls#117]
### NetBox access-list plugin version

v1.2.1

### NetBox version

v3.4.2

### Steps to Reproduce

I've set my local_requirements.txt and the configuration.py parameter for this plugin like so :

`napalm >= 4.0.0
netbox-qrcode >= 0.0.8
netbox-topology-views >= 3.2.1
netbox-bgp >= 0.9.0
netbox-acls >= 1.2.1`

```
# Enable installed plugins. Add the name of each plugin to the list.
PLUGINS = ['netbox_qrcode', 'netbox_topology_views', 'netbox_bgp', 'netbox_acls']

# Plugins configuration settings. These settings are used by various plugins that the user may have installed.
# Each key in the dictionary is the name of an installed plugin and its value is a dictionary of settings.
# PLUGINS_CONFIG = {
#     'my_plugin': {
#         'foo': 'bar',
#         'buzz': 'bazz'
#     }
# }
PLUGINS_CONFIG = {
    'netbox_qrcode': {
        'with_text': True,
        'text_fields': ['name', 'serial'],
        'font': 'ArialMT',
        'custom_text': None,
        'text_location': 'right',
        'qr_version': 1,
        'qr_error_correction': 0,
        'qr_box_size': 4,
        'qr_border': 4,
        # per object options
        'cable': {
            'custom_text': None,
            'text_fields': [
                'a_terminations.device',
                'a_terminations.name',
                'b_terminations.device',
                'b_terminations.name'
             ]
         },
        'rack': {
            'text_fields': [
                'site',
                'name',
                'facility_id',
                'tenant'
            ]
        },
        'device': {
            'custom_text': None,
            'text_fields': [
                'name'
            ]
        }
    },
    'netbox_topology_views': {
        'device_img': ['leaf','spine'],
        'allow_coordinates_saving': True,
        'always_save_coordinates': True
    },
    'netbox_acls': {
            'top_level_menu': False
        }
}
```

### Expected Behavior

I'd supposed to see a new venv get made

### Observed Behavior

```
Running migrations:
  Applying netbox_acls.0002_alter_accesslist_options_and_more...Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "netbox_acls_aclextendedrule" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 349, in handle
    post_migrate_state = executor.migrate(
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/migrations/migration.py", line 130, in apply
    operation.database_forwards(
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/migrations/operations/fields.py", line 235, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 788, in alter_field
    self._alter_field(
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/backends/postgresql/schema.py", line 246, in _alter_field
    super()._alter_field(
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 1007, in _alter_field
    self.execute(
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 199, in execute
    cursor.execute(sql, params)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "netbox_acls_aclextendedrule" does not exist
```

**Comment by ryanmerolle** [comment]
@balpoint Try 1.2.2 since it addresses a migration issue for 3.4.  After that, please provide the the updated logs if it is still an issue.

I would also recommend bumping your netbox to 3.4.3 from 3.4.2.  Not for anything but it has some unrelated bug fixes.

**Comment by balpoint** [comment]
@ryanmerolle issue still persists:


```
local_requirements.txt (line 1)) (3.4)
Installing collected packages: pyserial, netbox-topology-views, netbox-bgp, netbox-acls, yamlordereddictloader, ttp, transitions, tenacity, qrcode, pyparsing, pyeapi, netutils, lxml, future, bcrypt, ttp-templates, textfsm, pynacl, netbox-qrcode, paramiko, ntc-templates, scp, ncclient, netmiko, junos-eznc, napalm
Successfully installed bcrypt-4.0.1 future-0.18.3 junos-eznc-2.6.6 lxml-4.9.2 napalm-4.0.0 ncclient-0.6.13 netbox-acls-1.2.2 netbox-bgp-0.9.0 netbox-qrcode-0.0.8 netbox-topology-views-3.2.1 netmiko-4.1.2 netutils-1.4.0 ntc-templates-3.2.0 paramiko-3.0.0 pyeapi-0.8.4 pynacl-1.5.0 pyparsing-3.0.9 pyserial-3.5 qrcode-7.3.1 scp-0.14.4 tenacity-8.1.0 textfsm-1.1.2 transitions-0.9.0 ttp-0.9.2 ttp-templates-0.3.2 yamlordereddictloader-0.4.0
Applying database migrations (python3 netbox/manage.py migrate)...
Operations to perform:
  Apply all migrations: admin, auth, circuits, contenttypes, dcim, django_rq, extras, ipam, netbox_acls, netbox_bgp, netbox_topology_views, sessions, social_django, taggit, tenancy, users, virtualization, wireless
Running migrations:
  Applying netbox_acls.0002_alter_accesslist_options_and_more...Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "netbox_acls_accesslist" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 349, in handle
    post_migrate_state = executor.migrate(
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/migrations/migration.py", line 130, in apply
    operation.database_forwards(
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/migrations/operations/fields.py", line 235, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 788, in alter_field
    self._alter_field(
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/backends/postgresql/schema.py", line 246, in _alter_field
    super()._alter_field(
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 1007, in _alter_field
    self.execute(
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 199, in execute
    cursor.execute(sql, params)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "netbox_acls_accesslist" does not exist

```

**Comment by ryanmerolle** [comment]
My only guess would be that I use Python 3.10.6 because I use the netbox-docker image to develop on.  All my tests use that image.  I'll keep poking around, but since I cannot reproduce the issue, it may be challenging.

I am not sure why the table would not even been seen.

**Comment by abhi1693** [comment]
The only way I could reproduce this was by installing an older version of the plugin that had a single migration file and then dropping the ACL table in my db and then trying to upgrade the plugin. Only in this condition I got the exact same issue.

Could you check if your db has the tables?

**Comment by ryanmerolle** [comment]
Ah I was just not really thinking and multitasking when I mentioned 3.10.6.  This has to be some issue with the db tables.

Maybe disable the plugin, start up netbox, and then re-enable and restart.

**Comment by balpoint** [comment]
Upgraded python to 3.10 on a test install for netbox but am getting the same error

```
Operations to perform:
  Apply all migrations: admin, auth, circuits, contenttypes, dcim, django_rq, extras, ipam, netbox_acls, netbox_bgp, netbox_topology_views, sessions, social_django, taggit, tenancy, users, virtualization, wireless
Running migrations:
  Applying netbox_acls.0002_alter_accesslist_options_and_more...Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "netbox_acls_aclextendedrule" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 349, in handle
    post_migrate_state = executor.migrate(
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/migrations/migration.py", line 130, in apply
    operation.database_forwards(
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/migrations/operations/fields.py", line 235, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/backends/base/schema.py", line 788, in alter_field
    self._alter_field(
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/backends/postgresql/schema.py", line 246, in _alter_field
    super()._alter_field(
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/backends/base/schema.py", line 1007, in _alter_field
    self.execute(
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/backends/base/schema.py", line 199, in execute
    cursor.execute(sql, params)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "netbox_acls_aclextendedrule" does not exist
```

Also tried disabling the plugin restarting netbox and enabling the plugin this just results in the gui telling me for every page that the database tables do not exists:

`relation "netbox_acls_aclstandardrule" does not exist
`

**Comment by ryanmerolle** [comment]
Did you delete all the tables like mentioned?  You would then loose all netbox-acl data.

[Remove the plugin in its entirety](https://docs.netbox.dev/en/stable/plugins/#removing-plugins), start netbox, then reinstall

**Comment by balpoint** [comment]
yes i did clear all database entries as specified in the remove plugin documentation:

```
netbox=> \dt netbox_acls_*
Did not find any relation named "netbox_acls_*".
netbox=> \q
(venv) [root@app1-test-netbox.triple.ams2 ~ ]# sudo systemctl restart netbox
(venv) [root@app1-test-netbox.triple.ams2 ~ ]# sudo systemctl restart netbox-rq.service
(venv) [root@app1-test-netbox.triple.ams2 ~ ]# pip install netbox-acls
Collecting netbox-acls
  Using cached netbox_acls-1.2.2-py3-none-any.whl (38 kB)
Installing collected packages: netbox-acls
Successfully installed netbox-acls-1.2.2
(venv) [root@app1-test-netbox.triple.ams2 ~ ]# vim /opt/netbox/netbox/netbox/configuration.py
(venv) [root@app1-test-netbox.triple.ams2 ~ ]# sudo systemctl restart netbox-rq.service netbox
```

Still having the same issue that the plugin is showing in the UI but when clicking on a page it gives the same error:

```
relation "netbox_acls_accesslist" does not exist
LINE 1: ...acls_aclstandardrule"."id")) AS "rule_count" FROM "netbox_ac
```
 and also when performing a ./manage.py migrate it still says the tables are not defined
 
 so when checking the DB after installing plugin and enabling it it show nothing :
 
 ```
 netbox=> \dt netbox_acls_*
Did not find any relation named "netbox_acls_*".
 ```

no idea what to do next :/

**Comment by abhi1693** [comment]
Those instructions are missing a step. Do this as well in your PSQL shell

```
select * from django_migrations where app='netbox_acls';
```

If the command returns an output, delete those rows

```
delete from django_migrations where app='netbox_acls';
```

**Comment by balpoint** [comment]
@abhi1693 thanks for those command's because indeed i got output from the first one.

```
netbox=> select * from django_migrations where app='netbox_acls';
 id  |     app     |     name     |            applied
-----+-------------+--------------+-------------------------------
 492 | netbox_acls | 0001_initial | 2022-10-26 14:45:34.321802+02
(1 row)
netbox=> delete from django_migrations where app='netbox_acls';
DELETE 1
```

creating a new venv for netbox now resulting in correct migrations:

```
Running migrations:
  Applying netbox_acls.0001_initial... OK
  Applying netbox_acls.0002_alter_accesslist_options_and_more... OK
  Applying netbox_acls.0003_netbox_acls... OK
```

Everything seems to be working fine will do some more testing on functionality!

**Comment by balpoint** [comment]
Plugin seems to be working just fine, maybe the official docs could get updates ?
