### ISSUE TITLE
[Bug]: ./test.sh failing with errors

### ISSUE THREAD

**Issue by cruse1977** [netbox-community/netbox-acls#210]
### NetBox access-list plugin version

v1.6.1

### NetBox version

v4.0.11

### Steps to Reproduce

 Run ./test.sh

### Expected Behavior

Tests Complete as expected

### Observed Behavior

Exception occurs - 

test_root (netbox_acls.tests.test_api.AppTest.test_root) ... ok

======================================================================
FAIL: test_graphql_get_object (netbox_acls.tests.test_api.ACLTestCase.test_graphql_get_object)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/test/utils.py", line 443, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/netbox/utilities/testing/api.py", line 555, in test_graphql_get_object
    self.assertIn('errors', data)
AssertionError: 'errors' not found in {'data': {'access_list': {'changelog': [], 'display': 'testacl1', 'class_type': 'AccessList', 'tags': [], 'custom_fields': {}, 'assigned_object_type': {'id': '36'}, 'id': '1', 'created': '2024-09-12T21:47:09.050112+00:00', 'last_updated': '2024-09-12T21:47:09.050119+00:00', 'custom_field_data': {}, 'name': 'testacl1', 'assigned_object_id': 1, 'type': 'standard', 'default_action': 'deny', 'comments': ''}}}

----------------------------------------------------------------------
Ran 22 tests in 0.493s

FAILED (failures=1, skipped=1)

**Comment by cruse1977** [comment]
https://github.com/netbox-community/netbox/issues/15559
